services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WapplerSystems\Proxy\:
    resource: '../Classes/*'

  cache.proxy_responses:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['proxy_responses']

  cache.proxy_url_seen:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['proxy_url_seen']

  WapplerSystems\Proxy\Service\UrlDiscoveryLogger:
    public: true
    arguments:
      $cache: '@cache.proxy_url_seen'

  WapplerSystems\Proxy\Command\FlushCacheCommand:
    tags:
      - name: console.command
        command: 'proxy:cache:flush'

  WapplerSystems\Proxy\Proxy:
    public: true
    arguments:
      $cache: '@cache.proxy_responses'