services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WapplerSystems\Proxy\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  #cache.proxy_assets:
  #  class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
  #  factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
  #  arguments: ['proxy_assets']

  #WapplerSystems\Proxy\Proxy:
    #public: true
    #arguments:
      #$cache: '@cache.proxy_assets'
